source 'git@github.com:osakila/private-spec-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '15.0'

target 'SdkSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SdkSample
  pod 'THETAClientPrivateTmp', '0.0.1'
  pod 'THETAClient', '1.1.0'
end
